export const ADMIN_FETCH_CATEGORY = 'ADMIN_FETCH_CATEGORY';

export const ADMIN_DEL_CATEGORY_SUCCESS = 'ADMIN_DEL_CATEGORY_SUCCESS';
export const ADMIN_DEL_CATEGORY_FALSE = 'ADMIN_DEL_CATEGORY_FALSE';

export const ADMIN_ADD_CATEGORY_SUCCESS = 'ADMIN_ADD_CATEGORY_SUCCESS';
export const ADMIN_ADD_CATEGORY_FALSE = 'ADMIN_ADD_CATEGORY_FALSE';

export const ADMIN_EDIT_CATEGORY_SUCCESS = 'ADMIN_EDIT_CATEGORY_SUCCESS';
export const ADMIN_EDITTING_CATEGORY = 'ADMIN_EDITTING_CATEGORY';

export const FETCH_CATEGORY = 'FETCH_CATEGORY';